test-sort: test-sort.o sort.o
	g++ -o test-sort test-sort.o sort.o
	./test-sort
	$(RM) -rf *.o *.csv test-sort

sort.o: sort.cpp sort.hpp
	g++ -std=c++14 -c sort.cpp

test-sort.o: test-sort.cpp sort.hpp
	g++ -std=c++14 -c test-sort.cpp

# Check if CSV files are generated by the program main
check-csv:
	$(RM) -f *.csv
	$(MAKE) main
	./main
	@if [ -e results.csv ]; then \
		echo "CSV file found"; \
	else \
		echo "No CSV file found"; \
		$(MAKE) clean; \
		exit 1; \
	fi
	$(MAKE) clean
	$(RM) -rf *.o *.csv test-sort

clean:
	rm -rf *.o *.csv test-sort
